Update test-monai-deploy-express.yml
Signed-off-by: JHancox <48477639+JHancox@users.noreply.github.com>

diff --git a/.github/workflows/test-monai-deploy-express.yml b/.github/workflows/test-monai-deploy-express.yml
--- a/.github/workflows/test-monai-deploy-express.yml
+++ b/.github/workflows/test-monai-deploy-express.yml
@@ -58,6 +58,12 @@ jobs:
               echo "WorkflowID Present"
           fi
 
+      - name: A/B Check
+        if: ${{ env.WID }} !='true'
+        run: |
+          echo "::error file={''},line={''},endLine={''},title={'Job Failed'}::{'No WorkflowID retured'}"
+          exit 1
+
       - name: Test WorkflowID
         continue-on-error: true
         run: |
